name: The Lab Daily Research Report

on:
  schedule:
    - cron: '0 13 * * *'   # 08:00 CDT (UTC-5)
    - cron: '0 14 * * *'   # 08:00 CST (UTC-6)
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  daily_report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Gate by Chicago local time (ensure 08:00)
        env:
          TZ: America/Chicago
        run: |
          echo "Local time: $(date)";
          HOUR=$(date +%H);
          if [ "$HOUR" != "08" ]; then
            echo "Not 08:00 local — exiting without generating report.";
            exit 0;
          fi
          
      - name: Generate research intelligence report
        run: |
          python scripts/generate_report.py
      
      - name: Update report index
        run: |
          python scripts/generate_report_index.py
          
      - name: Commit and push report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "feat(report): daily research intelligence $(date -u '+%Y-%m-%d')" && git push)

