name: The Lab Research Ingestion

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run research ingestion
        run: |
          python scripts/ingest_arxiv.py
          python scripts/ingest_huggingface.py
          python scripts/ingest_paperswithcode.py
          
      - name: Aggregate research data
        run: python scripts/aggregate.py
        
      - name: Mine research insights
        run: python scripts/mine_insights.py

      - name: Commit and push research data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(data): research ingestion $(date -u '+%Y-%m-%d %H:%M UTC')" && git push)
  
  # Optional: Deep research tracking for specific topics
  deep-research-scan:
    runs-on: ubuntu-latest
    needs: ingest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Track high-impact papers
        run: |
          # Re-run ingestion with focus on high-scoring papers
          python scripts/ingest_arxiv.py
        continue-on-error: true
      
      - name: Commit additional research data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(data): deep research scan $(date -u '+%Y-%m-%d %H:%M UTC')" && git push)
        continue-on-error: true

